export const mockCars = [
  {
    city_mpg: "12",
    class: "sedan",
    combination_mpg: "12",
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "electricity",
    highway_mpg: "14",
    make: "Toyota",
    model: "Corolla Altis",
    transmission: "Automatic",
    year: 2024,
  },
  {
    city_mpg: "15",
    class: "sedan",
    combination_mpg: "14",
    cylinders: 4,
    displacement: 1.2,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: "15",
    make: "Honda",
    model: "City 1.2",
    transmission: "Semi-Automatic",
    year: 2024,
  },
  {
    city_mpg: "17",
    class: "hatchback",
    combination_mpg: "15",
    cylinders: 3,
    displacement: 1.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: "17",
    make: "Suzuki",
    model: "Wagon R",
    transmission: "Manual",
    year: 2024,
  },
  {
    city_mpg: "10",
    class: "minivan",
    combination_mpg: "11",
    cylinders: 4,
    displacement: 1.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: "12",
    make: "Changan",
    model: "Kaarvan",
    transmission: "Manual",
    year: 2024,
  },
  {
    city_mpg: "19",
    class: "suv",
    combination_mpg: "12",
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "fuel",
    highway_mpg: "13",
    make: "Kia",
    model: "Sportage",
    transmission: "Automatic",
    year: 2024,
  },
  {
    city_mpg: "15",
    class: "suv",
    combination_mpg: "11",
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: "12",
    make: "Hyundai",
    model: "Tucson",
    transmission: "Semi-Automatic",
    year: 2024,
  },
];
